### PR TITLE
New `pyinstaller` GitHub Actions

### PR DESCRIPTION
**Pull request by ebb-earl-co**
This pull request brings new .yml files in .github/workflows: particularly, actions that use [`pyinstaller`](https://pyinstaller.org) to create binaries containing everything that `tidal-wave` needs to run: Python interpreter, Python dependencies, and an FFmpeg binary.

Work on the latter continues, as the binaries compiled are still rather large, and it's not clear exactly what minimal feature set is needed for the few file formats that `tidal-wave` interacts with.

### CODE REVIEW

**Comment by kgantchev** [comment]
Woosh! That looks fantastic! 2 min build time vs 8 min!

image

My name is Kiril Gantchev, I'm the CEO and co-founder of [FlyCI](https://flyci.net). Thanks for giving FlyCI a try. I hope you enjoy it and please feel free to reach out should you have any issues.

Best Regards,
Kiril Gantchev

Discord: [FlyCI](https://discord.gg/JyCjh439da) | Twitter: [flyciapp](https://twitter.com/flyciapp) | LinkedIn: [FlyCI](https://linkedin.com/company/flyci)

**Comment by eevan78** [comment]
Hi,
the [latest release 2024.1.13](https://github.com/ebb-earl-co/tidal-wave/releases/tag/2024.1.13) is missing the pyapp self-bootstrapping Windows binary. Can you please provide it?

**Comment by ebb-earl-co** [comment]
@eevan78 thank you for having pointed this out! I had not noticed that the automation had failed, so I will get it uploaded shortly.
Next time, can you raise an issue instead of commenting on the PR? That just helps me track things better.

**Comment by kgantchev** [comment]
Hi @ebb-earl-co,

Thanks for continuing to use FlyCI. We would love to feature your feedback on our website and add your project to [our case studies section](https://www.flyci.net/case-studies?utm_source=github&utm_medium=community&utm_campaign=recommend). It will highlight your project to our visitors and it will help us grow our community. Would you mind sharing a few thoughts? 

If you're OK with it, then I have a few quick questions that will help me prepare the case study: 

- **What motivated your choice to use FlyCI's MacOS runners, and what key benefits have you observed?** (Performance, compatibility, etc.)  
- **What has been your experience with the FlyCI runners so far?** 
- **What improvements have you noticed since integrating FlyCI's MacOS runners?** (e.g., performance enhancements, reduced build times, developer productivity, cost savings)

**Pull request merged**
